steps:
  - id: "Run docker-compose"
    name: 'docker/compose'
    args: ['-f', 'docker-compose.prod.yaml', 'up', '-d']

  - id: "Chown in /var/www"
    name: 'docker'
    args: ['exec','-u','root','-t','app','chown','-R','www-data:www-data','/var/www']

  - id: "Run docker ps"
    name: 'docker'
    args: ['ps']

  - id: "Run composer"
    name: 'docker'
    args: ['exec', '-t', 'app', 'composer', 'install']

  - id: "Run Key Generate"
    name: 'docker'
    args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'key:generate']

  - id: "Run Migrations"
    name: 'docker'
    args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'migrate']

  - id: "Run phpunit"
    name: 'docker'
    args: ['exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']
